SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
drop table if exists [CH01-01-Dimension].[DimCustomer]
CREATE TABLE [CH01-01-Dimension].[DimCustomer](
	[CustomerKey] [int] NOT NULL,
	[CustomerName] [varchar](30) NULL
) ON [PRIMARY]
GO
ALTER TABLE [CH01-01-Dimension].[DimCustomer] ADD  CONSTRAINT [PK__DimCusto__95011E6452BCF41C] PRIMARY KEY CLUSTERED 
(
	[CustomerKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
